export const seedQueries = [
  // --- Game Populer / Spesifik (Klasik, Tren & Terbaru) ---
  'bedwars',
  'shindo life',
  'blade ball',
  'royale high',
  'evade',
  'doors',
  'blox fruits',
  'pet simulator',
  'brookhaven',
  'adopt me',
  'murder mystery',
  'arsenal',
  'piggy',
  'bee swarm',
  'slap battles',
  'dress to impress',
  'soles rng',
  'fisch',
  'pressure',
  'deepwoken',
  'jujutsu shenanigan',
  'strongest battlegrounds',
  'pls donate',
  'hide and seek',
  'flee the facility',
  'tower of hell',
  'natural disaster',
  'work at a pizza place',
  'speed run 4',
  'theme park tycoon',
  'lumber tycoon',
  'block tales',
  'guts and blackpowder',
  'barotrauma',
  'decaying winter',
  'all star tower defense',
  'toilet tower defense',
  'pet catchers',
  'untitled boxing game',
  'bedwars lucky block',
  'break in',
  'jailbreak',
  'mad city',
  'phantom forces',
  'frontlines',

  // --- Genre & Kategori Populer ---
  'anime',
  'simulator',
  'tycoon',
  'obby',
  'horror',
  'tower defense',
  'fighting',
  'battle',
  'car',
  'driving',
  'survival',
  'roleplay',
  'school',
  'pets',
  'action',
  'adventure',
  'sports',
  'racing',
  'comedy',
  'naval',
  'arcade',
  'sandbox',
  'tabletop',
  'music',
  'rhythm',
  'educational',

  // --- Mekanik Gameplay & Sub-Genre Spesifik ---
  'clicker',
  'grinding',
  'dungeon',
  'raid',
  'rpg',
  'sandbox',
  'open world',
  'strategy',
  'puzzle',
  'parkour',
  'stealth',
  'fps',
  'shooter',
  'rng',
  'gacha',
  'roguelike',
  'roguelite',
  'tower climb',
  'dropper',
  'tycoon 2 player',
  'defense',
  'wrestling',
  'boxing',
  'obby but you are',
  'button simulator',
  'incremental',
  'auto battler',
  'aim trainer',
  'platformer',
  'minigames',
  'escape room',
  'deathrun',
  'tycoon 4 player',
  'wave based',
  'boss fight',
  'turn based',
  'bullet hell',
  'movement shooter',
  'destruction',
  'physics based',
  'clicker simulator',
  'multiplier',
  'rebirth system',
  'trade hangout',

  // --- Tema, Estetika & Sub-Kultur ---
  'military',
  'space',
  'sci-fi',
  'fantasy',
  'medieval',
  'cyberpunk',
  'zombie',
  'apocalypse',
  'ocean',
  'island',
  'magic',
  'ninja',
  'pirate',
  'superhero',
  'backrooms',
  'liminal space',
  'steampunk',
  'mythology',
  'egyptian',
  'wild west',
  'samurai',
  'wasteland',
  'underwater',
  'alien',
  'prehistoric',
  'dinosaur',
  'futuristic',
  'vintage',
  'spooky',
  'galaxy',
  'cartoon',
  'cottagecore',
  'gothic',
  'synthwave',
  'neon',
  'anime aesthetic',
  'y2k',
  'industrial',
  'military simulator',
  'historical',

  // --- Sosial, Kasual & Simulasi Kehidupan ---
  'hangout',
  'fashion',
  'cooking',
  'restaurant',
  'job',
  'city',
  'family',
  'multiplayer',
  'co-op',
  'trading',
  'showcase',
  'vibe',
  'cafe',
  'farming',
  'camping',
  'hotel',
  'aviation',
  'railway',
  'hospital',
  'daycare',
  'club',
  'salon',
  'police',
  'prison',
  'mansion',
  'neighborhood',
  'customization',
  'dress up',
  'house building',
  'pet adoption',
  'store manager',
  'supermarket',

  // --- Kata Kunci Meta, Fitur & Teknis Pencarian ---
  'free admin',
  'voice chat',
  'mic up',
  'hardcore',
  'easy',
  'impossible',
  'retro',
  'classic',
  'updated',
  'beta',
  'vr',
  'console',
  'mobile friendly',
  '1v1',
  'pvp',
  'pve',
  'no obby',
  'speedrun',
  'testing',
  'unshared',
  'alpha',
  'remake',
  'reborn',
  'multiplayer only',
  'singleplayer',
  'crossplay',
  'low poly',
  'realistic',
  'ragdoll',
  'physics',
  'modded',
  'infinite',
  'graphics test',
  'rtx showcases',
  'no lag',
  'shift lock',
  'r6',
  'r15',
  'custom rig',
  'ugc rewards',
  'free ugc',
  'event',
  'leaderboard',
]
