export const seedQueries = [
  // --- Game Populer / Spesifik (Tren & Klasik) ---
  /*'blox fruits',
  'grow a garden',
  'dead rails',
  'blue lock rivals',
  'dress to impress',
  'adopt me',
  'brookhaven',
  'psx',
  'pet simulator 99',
  'murder mystery 2',
  'bedwars',
  'shindo life',
  'blade ball',
  'royale high',
  'evade',
  'doors',

  // --- Genre & Kategori Populer ---
  'anime',
  'simulator',
  'tycoon',
  'obby',
  'horror',
  'tower defense',
  'fighting',
  'battle',
  'car',
  'driving',
  'survival',
  'roleplay',
  'school',
  'pets',*/

  // --- Perluasan Kategori: Gameplay & Mekanik ---
  'clicker',
  'grinding',
  ' dungeon',
  'raid',
  'rpg',
  'sandbox',
  'open world',
  'strategy',
  'puzzle',
  'parkour',
  'stealth',
  'fps',
  'shooter',

  // --- Perluasan Kategori: Tema & Estetika ---
  'military',
  'space',
  'sci-fi',
  'fantasy',
  'medieval',
  'cyberpunk',
  'zombie',
  'apocalypse',
  'ocean',
  'island',
  'magic',
  'ninja',
  'pirate',
  'superhero',

  // --- Perluasan Kategori: Sosial & Kasual ---
  'hangout',
  'fashion',
  'cooking',
  'restaurant',
  'job',
  'city',
  'family',
  'multiplayer',
  'co-op',
  'trading',

  // --- Kata Kunci Pencarian Umum / Meta ---
  'free admin',
  'voice chat',
  'mic up',
  'hardcore',
  'easy',
  'impossible',
  'retro',
  'classic',
  'updated',
  'beta',
]
